server:
  port: 7070
spring:
  application:
    name: client-a
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1