server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xiaowei_zxw/springcloud-Learn.git
          username: 502513206@qq.com
          password: a520201314
          # 仓库路径
          search-paths: SC-BOOK-CONFIG
  application:
    name: config-server