server:
  port: 8762
eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      zon1: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      zon2: http://localhost:8763/eureka/,http://localhost:8764/eureka/
    region: region-east
    availability-zones:
      region-east: zone1,zone2
  instance:
    prefer-ip-address: true
    hostname: localhost
    metadata-map: zone: zone1
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false