spring:
  cloud:
    gateway:
      routes:
        - id: jd_route
          uri: http://jd.com:80/
          predicates:
            - Path=/jd

  application:
    name: spring-cloud-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
      register-with-eureka: true
      fetch-register: true
      region: region-east
      availability-zones:
          region-east: zone1,zone2
      service-url:
        zon1: http://localhost:8761/eureka/,http://localhost:8762/eureka/
        zon2: http://localhost:8763/eureka/,http://localhost:8764/eureka/
  instance:
    metadataMap.zone: zone1

server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.nettu: debug